# Generated by Django 3.2.12 on 2022-04-30 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIPhoto',
            fields=[
                ('field', models.CharField(choices=[('banner', 'banner'), ('notice', 'notice ')], max_length=10, null=True, verbose_name='field')),
                ('indexnum', models.IntegerField(null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_file', models.ImageField(upload_to='ui-photo')),
            ],
        ),
    ]
