# Generated by Django 3.2.12 on 2022-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_smartresultqrphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartresultqrphoto',
            name='photo_file',
            field=models.ImageField(upload_to='qr-code-photo'),
        ),
    ]
