# Generated by Django 3.2.12 on 2022-03-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user_id',
            new_name='member_id',
        ),
    ]
