# Generated by Django 3.2.12 on 2022-03-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20220305_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='supports',
            old_name='uuid',
            new_name='id',
        ),
    ]
