# Generated by Django 3.2.12 on 2022-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_user_id_subscribe_member_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supports',
            new_name='Support',
        ),
    ]
