# Generated by Django 3.2.12 on 2022-04-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_rename_supports_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='age',
            field=models.IntegerField(null=True, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='support',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('N', '어느쪽도 아님(None)')], default='N', max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='support',
            name='income_ratio',
            field=models.IntegerField(null=True, verbose_name='한국장학재단 기준 소득분위'),
        ),
        migrations.AddField(
            model_name='support',
            name='located_in',
            field=models.CharField(max_length=50, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='support',
            name='number_of_households',
            field=models.IntegerField(null=True, verbose_name='가구수'),
        ),
        migrations.AlterField(
            model_name='support',
            name='detail',
            field=models.TextField(verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='support',
            name='end_date',
            field=models.DateTimeField(verbose_name='마감 날짜'),
        ),
        migrations.AlterField(
            model_name='support',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='주관사'),
        ),
        migrations.AlterField(
            model_name='support',
            name='qualifications',
            field=models.TextField(null=True, verbose_name='지원자격'),
        ),
        migrations.AlterField(
            model_name='support',
            name='start_date',
            field=models.DateTimeField(verbose_name='시작 날짜'),
        ),
        migrations.AlterField(
            model_name='support',
            name='submit_link',
            field=models.URLField(blank=True, null=True, verbose_name='관련 링크'),
        ),
    ]
