# Generated by Django 3.2.12 on 2022-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20220412_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='organizer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
