# Generated by Django 3.2.12 on 2022-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_support_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='support',
            name='organizer',
            field=models.CharField(max_length=50, null=True, verbose_name='주관사'),
        ),
    ]
