# Generated by Django 3.2.12 on 2022-04-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='구독할 채널 작명'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='organizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='관련 제도'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='organizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='관심있는 분야'),
        ),
    ]
