# Generated by Django 3.2.12 on 2022-04-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_supportnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportnotification',
            options={'verbose_name': 'SupportNotification'},
        ),
    ]
