# Generated by Django 3.2.12 on 2022-04-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0009_alter_fcmdevice_user'),
        ('support', '0011_alter_supportnotification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportnotification',
            name='active',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='registration_id',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='user',
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='user_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice', verbose_name='유저 디바이스 정보'),
        ),
    ]
