# Generated by Django 3.2.12 on 2022-04-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0009_alter_fcmdevice_user'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('support', '0012_auto_20220421_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportnotification',
            options={},
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='last_logined',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='sched_noti',
        ),
        migrations.RemoveField(
            model_name='supportnotification',
            name='user_device_info',
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='periodictask_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.support', verbose_name='제도/지원금'),
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='organizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='정부 및 기관, 주관사'),
        ),
        migrations.CreateModel(
            name='SupportScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_noti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.supportnotification', verbose_name='예정되어있는 알림')),
                ('user_device_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice', verbose_name='유저 디바이스 정보')),
            ],
            options={
                'verbose_name': 'SupportScheduledNotification',
            },
        ),
    ]
