# Generated by Django 3.2.12 on 2022-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20220425_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportschedulednotification',
            name='noti_on_time',
            field=models.DateTimeField(default=1, verbose_name='푸시알림 전송할 시간'),
            preserve_default=False,
        ),
    ]
