# Generated by Django 3.2.12 on 2022-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_alter_supportschedulednotification_noti_on_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportschedulednotification',
            name='noti_on_time',
            field=models.DateTimeField(null=True, verbose_name='푸시알림 전송할 시간'),
        ),
    ]
