# Generated by Django 3.2.12 on 2022-04-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_alter_supportschedulednotification_noti_on_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportschedulednotification',
            name='noti_on_or_off',
        ),
        migrations.RemoveField(
            model_name='supportschedulednotification',
            name='noti_on_time',
        ),
    ]
