# Generated by Django 3.2.12 on 2022-04-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0024_remove_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='organizer_id',
        ),
    ]
