# Generated by Django 3.2.12 on 2022-04-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0025_remove_channel_organizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='organizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='관련 제도'),
        ),
    ]
