# Generated by Django 3.2.12 on 2022-04-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_memberfcmdevice'),
        ('support', '0027_support_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportschedulednotification',
            name='member_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.memberfcmdevice', verbose_name='멤버 디바이스 정보'),
        ),
    ]
