# Generated by Django 3.2.12 on 2022-05-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0009_alter_fcmdevice_user'),
        ('user', '0007_memberfcmdevice'),
        ('support', '0029_supportbookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportnotification',
            options={'verbose_name': 'SupportNotification'},
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='member_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.memberfcmdevice', verbose_name='멤버 디바이스 정보'),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='noti_on_or_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='noti_on_time',
            field=models.DateTimeField(null=True, verbose_name='푸시알림 전송할 시간'),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='user_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice', verbose_name='유저 디바이스 정보'),
        ),
    ]
