# Generated by Django 3.2.12 on 2022-05-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_memberfcmdevice'),
        ('fcm_django', '0009_alter_fcmdevice_user'),
        ('support', '0030_auto_20220501_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportnotification',
            name='member_device_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.memberfcmdevice', verbose_name='멤버 디바이스 정보'),
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='noti_on_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='푸시알림 전송할 시간'),
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='organizer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='정부 및 기관, 주관사'),
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='support_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.support', verbose_name='제도/지원금'),
        ),
        migrations.AlterField(
            model_name='supportnotification',
            name='user_device_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice', verbose_name='유저 디바이스 정보'),
        ),
    ]
