# Generated by Django 3.2.12 on 2022-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0031_auto_20220501_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='colored',
            field=models.CharField(choices=[('pink', 'pink'), ('yellow', 'yellow ')], max_length=10, null=True, verbose_name='색깔 분류'),
        ),
    ]
