# Generated by Django 3.2.12 on 2022-05-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0032_auto_20220501_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.support', verbose_name='제도/지원금')),
            ],
            options={
                'verbose_name': 'RecordingList',
            },
        ),
    ]
