# Generated by Django 3.2.12 on 2022-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0033_recordinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='support',
            name='detail',
            field=models.TextField(blank=True, verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='support',
            name='income_ratio',
            field=models.IntegerField(blank=True, null=True, verbose_name='한국장학재단 기준 소득분위'),
        ),
        migrations.AlterField(
            model_name='support',
            name='located_in',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='support',
            name='number_of_households',
            field=models.IntegerField(blank=True, null=True, verbose_name='가구수'),
        ),
        migrations.AlterField(
            model_name='support',
            name='qualifications',
            field=models.TextField(blank=True, null=True, verbose_name='지원자격'),
        ),
    ]
