# Generated by Django 3.2.12 on 2022-05-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0035_alter_support_number_of_households'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='age',
        ),
        migrations.RemoveField(
            model_name='support',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='support',
            name='income_ratio',
        ),
        migrations.RemoveField(
            model_name='support',
            name='number_of_households',
        ),
        migrations.AddField(
            model_name='support',
            name='biz_id',
            field=models.CharField(max_length=50, null=True, verbose_name='정책 번호'),
        ),
        migrations.AddField(
            model_name='support',
            name='notice',
            field=models.TextField(blank=True, null=True, verbose_name='유의 사항'),
        ),
        migrations.AlterField(
            model_name='support',
            name='qualifications',
            field=models.TextField(blank=True, null=True, verbose_name='신청 대상'),
        ),
    ]
