# Generated by Django 3.2.12 on 2022-05-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0036_auto_20220510_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='biz_id',
            new_name='bizId',
        ),
        migrations.AddField(
            model_name='support',
            name='plcyTpNm',
            field=models.TextField(blank=True, null=True, verbose_name='정책 유형'),
        ),
        migrations.AddField(
            model_name='support',
            name='rqutPrdCn',
            field=models.TextField(blank=True, null=True, verbose_name='신청 기간'),
        ),
    ]
