# Generated by Django 3.2.12 on 2022-05-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0037_auto_20220510_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
