# Generated by Django 3.2.12 on 2022-05-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0038_alter_support_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마감 날짜'),
        ),
        migrations.AlterField(
            model_name='support',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작 날짜'),
        ),
    ]
