# Generated by Django 3.2.12 on 2022-05-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0040_auto_20220510_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['end_date']},
        ),
    ]
