# Generated by Django 3.2.12 on 2022-05-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0041_alter_support_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-end_date']},
        ),
    ]
