# Generated by Django 3.2.12 on 2022-05-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0042_alter_support_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportnotification',
            name='interval_time',
            field=models.IntegerField(blank=True, default=7, null=True, verbose_name='인터벌 시간 설정'),
        ),
    ]
