# Generated by Django 3.2.12 on 2022-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0044_auto_20220512_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=50, null=True, verbose_name='구독할 채널 작명'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_name',
            field=models.CharField(max_length=50, null=True, verbose_name='관심있는 분야'),
        ),
    ]
