# Generated by Django 3.2.12 on 2022-05-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0045_auto_20220512_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='colored',
            field=models.CharField(choices=[('한국 장학 재단 .zip', '한국 장학 재단 .zip'), ('자취생을 위한 .zip', '자취생을 위한 .zip '), ('For .경기도인 대학생', 'For .경기도인 대학생'), ('각종 혜택/꿀팁 모음', '각종 혜택/꿀팁 모음')], max_length=50, null=True, verbose_name='색깔 분류'),
        ),
    ]
