# Generated by Django 3.2.12 on 2022-05-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0046_alter_subscribe_colored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='colored',
            new_name='channel_name',
        ),
    ]
