# Generated by Django 3.2.12 on 2022-05-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0051_auto_20220512_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='organizer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='관련 기관'),
        ),
    ]
