# Generated by Django 3.2.12 on 2022-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0052_alter_channel_organizer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='member_id',
            new_name='member_list',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='colored',
            field=models.CharField(choices=[('pink', 'pink'), ('yellow', 'yellow ')], max_length=10, null=True, verbose_name='카테고리'),
        ),
    ]
