# Generated by Django 3.2.12 on 2022-05-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0053_auto_20220512_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='member_list',
            new_name='member_id',
        ),
    ]
