# Generated by Django 3.2.12 on 2022-05-12 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0054_rename_member_list_channel_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='member_id',
        ),
        migrations.AddField(
            model_name='channel',
            name='member_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='member_id',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='member_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.support', verbose_name='관련있는 제도'),
        ),
    ]
