# Generated by Django 3.2.12 on 2022-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0055_auto_20220512_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='detail_field',
            field=models.CharField(blank=True, choices=[('1', '다자녀 가정'), ('2', '한부모 가정'), ('3', '다문화 가정'), ('4', '현역 군인 및 군무원의 자녀'), ('5', '장애인, 장애우'), ('6', '기타')], default='1', max_length=6, null=True, verbose_name='분야'),
        ),
    ]
