# Generated by Django 3.2.12 on 2022-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0056_support_detail_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='job_info',
            field=models.CharField(blank=True, choices=[('학생', '학생'), ('직장인', '직장인'), ('프리랜서', '프리랜서')], default='1', max_length=6, null=True, verbose_name='분야'),
        ),
        migrations.AddField(
            model_name='support',
            name='plcyTpNm_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='정책 유형 - 세부 필드'),
        ),
    ]
