# Generated by Django 3.2.12 on 2022-05-15 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0057_auto_20220514_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='member_id',
        ),
        migrations.AddField(
            model_name='channel',
            name='member_id',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='support',
            name='detail_field',
            field=models.CharField(blank=True, choices=[('1', '다자녀 가정'), ('2', '한부모 가정'), ('3', '다문화 가정'), ('4', '현역 군인 및 군무원의 자녀'), ('5', '장애인, 장애우'), ('6', '기타')], default='1', max_length=6, null=True, verbose_name='스마트설계 - 분야'),
        ),
        migrations.AlterField(
            model_name='support',
            name='job_info',
            field=models.CharField(blank=True, choices=[('학생', '학생'), ('직장인', '직장인'), ('프리랜서', '프리랜서')], default='1', max_length=6, null=True, verbose_name='직업'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리')),
                ('channel_name', models.CharField(max_length=50, null=True, verbose_name='구독할 채널 작명')),
                ('organizer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.organization', verbose_name='관련 기관')),
                ('support_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='support.support', verbose_name='관련 제도')),
            ],
        ),
    ]
