# Generated by Django 3.2.12 on 2022-05-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0058_auto_20220515_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='colored',
            field=models.CharField(choices=[('pink', 'pink'), ('yellow', 'yellow ')], max_length=10, null=True, verbose_name='카테고리'),
        ),
    ]
