# Generated by Django 3.2.12 on 2022-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0059_auto_20220515_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리 명'),
        ),
        migrations.AlterField(
            model_name='category',
            name='colored',
            field=models.CharField(choices=[('blue', '취업(blue)'), ('cyan', '창업(cyan)'), ('pink', '주거/금융(pink)'), ('green', '생활/복지(green)'), ('purple', '정책참여(purple))'), ('gray', '코로나19(gray)')], max_length=10, null=True, verbose_name='색깔 분류'),
        ),
    ]
