# Generated by Django 3.2.12 on 2022-05-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0060_auto_20220515_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='submit_link',
            field=models.TextField(blank=True, null=True, verbose_name='신청 링크'),
        ),
    ]
