# Generated by Django 3.2.12 on 2022-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0061_alter_support_submit_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colored',
            field=models.CharField(choices=[('blue', '취업(blue)'), ('cyan', '창업(cyan)'), ('pink', '주거/금융(pink)'), ('green', '생활/복지(green)'), ('purple', '정책참여(purple)'), ('gray', '코로나19(gray)')], max_length=10, null=True, verbose_name='색깔 분류'),
        ),
    ]
