# Generated by Django 3.2.12 on 2022-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0065_alter_support_detail_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='detail_field',
            field=models.CharField(blank=True, choices=[('1', '취약 계층'), ('2', '다자녀 가정'), ('3', '다문화 가정'), ('4', '코로나 19 지원 대상'), ('5', '장애인, 장애우'), ('6', '해당 없음')], default='6', max_length=6, null=True, verbose_name='스마트설계 - 분야'),
        ),
    ]
