# Generated by Django 3.2.12 on 2022-03-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth',
            new_name='AuthSMS',
        ),
    ]
