# Generated by Django 3.2.12 on 2022-03-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_uuid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
