# Generated by Django 3.2.12 on 2022-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_auth_authsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='실거주지'),
        ),
        migrations.AddField(
            model_name='member',
            name='locatedin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='학교 및 소재지'),
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호'),
        ),
    ]
