# Generated by Django 3.2.12 on 2022-03-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220331_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='휴대폰 번호'),
        ),
    ]
