# Generated by Django 3.2.12 on 2022-04-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('N', '어느쪽도 아님(None)')], default='N', max_length=1, null=True, verbose_name='성별'),
        ),
    ]
