# Generated by Django 3.2.12 on 2022-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_cityaddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
