# Generated by Django 3.2.12 on 2022-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_member_privacy_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='개인정보 동의'),
        ),
    ]
