# Generated by Django 3.2.12 on 2022-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_member_is_smart_recommed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
